[package]

name = "conduit-router"
version = "0.9.0-alpha.6"
authors = ["wycats@gmail.com"]
license = "MIT"
description = "Router middleware for conduit based on route-recognizer"
repository = "https://github.com/conduit-rust/conduit-router"

[dependencies]
conduit = "0.9.0-alpha.5"
route-recognizer = "0.3"
tracing = "0.1.25"

[dev-dependencies]
conduit-test = "0.9.0-alpha.4"
lazy_static = "1.4.0"
tracing-subscriber = "0.2.16"
